### ISSUE TITLE
Cannot find the "ridgeCPM_vector" function

### ISSUE THREAD

**Issue by GaelVaroquaux** [abigailsgreene/taskFC#1]
I cannot find the "ridgeCPM_vector" function. According to the readme, I believe that it should be in YaleMRRC/CPM repository, but it doesn't seem to be there:
https://github.com/YaleMRRC/CPM/search?q=ridgeCPM_vector&unscoped_q=ridgeCPM_vector

Am I doing something wrong? Thanks!

**Comment by abigailsgreene** [comment]
Sorry about that - the code can now be found in the YaleMRRC/CPM repository, at https://github.com/YaleMRRC/CPM/blob/master/matlab/func/ridgeCPM_vector.m

Let me know if you have any trouble accessing it!
________________________________

**Comment by GaelVaroquaux** [comment]
Thank you very much! That's very helpful.
